// ==========================================
// LINGUALEARN - LOT 2 : Banque Vocabulaire
// Données initiales : EN (Travel, Meetings, Risk) A1-B2 + ES (Travel) A1-A2
// ==========================================

import { VocabWord } from './bankTypes';

let nextId = 1;
const w = (language: string, word_target: string, word_fr: string, definition_en: string, example_en: string, theme: string, level: string, type: string, is_grc: boolean, definition_fr?: string, definition_lang?: string): VocabWord => ({
  id: `vocab_${nextId++}`, language, word_target, word_fr, definition_en, example_en, theme, level, type, is_grc, definition_fr, definition_lang,
});

export const BANK_VOCABULARY: VocabWord[] = [
  // ===== ANGLAIS - TRAVEL - A1 =====
  w('en','hello','bonjour','A greeting used when meeting someone','Hello, how are you?','travel','A1','interjection',false,'Un salut utilisé à la rencontre de quelqu\'un'),
  w('en','goodbye','au revoir','A farewell expression','Goodbye, see you tomorrow!','travel','A1','interjection',false,'Une expression d\'adieu'),
  w('en','please','s\'il vous plaît','A polite word used when asking','Please give me a ticket.','travel','A1','adverb',false,'Un mot poli utilisé lors d\'une demande'),
  w('en','thank you','merci','An expression of gratitude','Thank you for your help.','travel','A1','interjection',false,'Une expression de gratitude'),
  w('en','ticket','billet','A piece of paper giving right to travel','I need a ticket to London.','travel','A1','noun',false,'Un morceau de papier donnant le droit de voyager'),
  w('en','airport','aéroport','A place where planes take off and land','The airport is very big.','travel','A1','noun',false,'Un endroit où les avions décollent et atterrissent'),
  w('en','hotel','hôtel','A place to sleep when traveling','We booked a hotel near the beach.','travel','A1','noun',false,'Un lieu pour dormir lors d\'un voyage'),
  w('en','train','train','A vehicle that runs on rails','The train leaves at 9 am.','travel','A1','noun',false,'Un véhicule qui circule sur des rails'),
  w('en','bus','bus','A large vehicle for public transport','I take the bus every day.','travel','A1','noun',false,'Un grand véhicule pour les transports publics'),
  w('en','map','carte','A drawing of a region or country','Can you show me on the map?','travel','A1','noun',false,'Un dessin d\'une région ou d\'un pays'),
  w('en','passport','passeport','An official document for travel','Don\'t forget your passport.','travel','A1','noun',false,'Un document officiel pour voyager'),
  w('en','suitcase','valise','A case for carrying clothes','My suitcase is heavy.','travel','A1','noun',false,'Un étui pour transporter des vêtements'),
  w('en','taxi','taxi','A car for hire','Let\'s take a taxi to the hotel.','travel','A1','noun',false,'Une voiture de location'),
  w('en','restaurant','restaurant','A place to eat meals','There is a nice restaurant nearby.','travel','A1','noun',false,'Un lieu pour prendre des repas'),
  w('en','water','eau','A clear liquid for drinking','Can I have some water, please?','travel','A1','noun',false,'Un liquide clair à boire'),
  w('en','room','chambre','A space in a building for sleeping','The room has a nice view.','travel','A1','noun',false,'Un espace dans un bâtiment pour dormir'),
  w('en','money','argent','Currency used to buy things','I need to change some money.','travel','A1','noun',false,'Monnaie utilisée pour acheter des choses'),
  w('en','beach','plage','A sandy area by the sea','Let\'s go to the beach.','travel','A1','noun',false,'Une zone sablonneuse près de la mer'),
  w('en','city','ville','A large town','Paris is a beautiful city.','travel','A1','noun',false,'Une grande ville'),
  w('en','help','aide','Assistance given to someone','I need help with my luggage.','travel','A1','noun',false,'L\'assistance donnée à quelqu\'un'),

  // ===== ANGLAIS - TRAVEL - A2 =====
  w('en','luggage','bagages','Bags and suitcases for travel','Where is the luggage carousel?','travel','A2','noun',false),
  w('en','departure','départ','The act of leaving','The departure is at 3 pm.','travel','A2','noun',false),
  w('en','arrival','arrivée','The act of arriving','Check the arrival time.','travel','A2','noun',false),
  w('en','reservation','réservation','A booking in advance','I have a reservation for two.','travel','A2','noun',false),
  w('en','flight','vol','A journey by air','The flight takes 2 hours.','travel','A2','noun',false),
  w('en','currency','devise','The money used in a country','What currency do they use?','travel','A2','noun',false),
  w('en','guidebook','guide','A book with travel information','I bought a guidebook for Italy.','travel','A2','noun',false),
  w('en','accommodation','hébergement','A place to stay','We found cheap accommodation.','travel','A2','noun',false),
  w('en','destination','destination','The place you are going to','What is your destination?','travel','A2','noun',false),
  w('en','delay','retard','When something is late','There is a 30-minute delay.','travel','A2','noun',false),
  w('en','boarding pass','carte d\'embarquement','A document needed to board a plane','Show your boarding pass here.','travel','A2','noun',false),
  w('en','customs','douane','The place at borders for checks','We went through customs quickly.','travel','A2','noun',false),
  w('en','exchange rate','taux de change','The rate for converting currencies','The exchange rate is favorable.','travel','A2','noun',false),
  w('en','souvenir','souvenir','An object bought to remember a trip','I bought a souvenir for my mom.','travel','A2','noun',false),
  w('en','itinerary','itinéraire','A planned route of travel','Our itinerary includes Rome.','travel','A2','noun',false),
  w('en','check-in','enregistrement','The process at a hotel or airport','Check-in starts at 2 pm.','travel','A2','noun',false),
  w('en','checkout','départ hôtel','Leaving a hotel','Checkout is before 11 am.','travel','A2','noun',false),
  w('en','tour','visite','A journey for sightseeing','We took a tour of the old city.','travel','A2','noun',false),
  w('en','direction','direction','The way to go','Can you give me directions?','travel','A2','noun',false),
  w('en','platform','quai','Where you wait for a train','The train departs from platform 3.','travel','A2','noun',false),

  // ===== ANGLAIS - TRAVEL - B1 =====
  w('en','jet lag','décalage horaire','Tiredness from changing time zones','I always get jet lag after long flights.','travel','B1','noun',false),
  w('en','layover','escale','A stop between flights','We have a 3-hour layover in Dubai.','travel','B1','noun',false),
  w('en','backpacking','randonnée sac-à-dos','Traveling cheaply with a backpack','Backpacking across Europe was amazing.','travel','B1','noun',false),
  w('en','all-inclusive','tout compris','Including all meals and drinks','We booked an all-inclusive resort.','travel','B1','adjective',false),
  w('en','off-season','hors saison','Period with fewer tourists','Prices are lower in the off-season.','travel','B1','noun',false),
  w('en','scenic','pittoresque','Having beautiful natural scenery','The scenic route takes longer.','travel','B1','adjective',false),
  w('en','to book','réserver','To make a reservation','I need to book a hotel room.','travel','B1','verb',false),
  w('en','to cancel','annuler','To stop a reservation','I had to cancel my flight.','travel','B1','verb',false),
  w('en','to explore','explorer','To travel to discover new things','Let\'s explore the old town.','travel','B1','verb',false),
  w('en','round trip','aller-retour','A journey to a place and back','I bought a round trip ticket.','travel','B1','noun',false),
  w('en','sightseeing','tourisme','Visiting interesting places','We spent the day sightseeing.','travel','B1','noun',false),
  w('en','travel insurance','assurance voyage','Protection for travel problems','Always buy travel insurance.','travel','B1','noun',false),
  w('en','abroad','à l\'étranger','In a foreign country','She studied abroad for a year.','travel','B1','adverb',false),
  w('en','hitchhike','faire de l\'auto-stop','To travel by getting free rides','We hitchhiked from Paris to Lyon.','travel','B1','verb',false),
  w('en','overnight','de nuit','Lasting through the night','We took an overnight train.','travel','B1','adjective',false),
  w('en','landmark','monument','A notable building or place','The Eiffel Tower is a famous landmark.','travel','B1','noun',false),
  w('en','seaside','bord de mer','An area next to the sea','We rented a house by the seaside.','travel','B1','noun',false),
  w('en','backpack','sac à dos','A bag carried on your back','My backpack weighs 10 kg.','travel','B1','noun',false),
  w('en','hostel','auberge de jeunesse','A cheap place for young travelers','The hostel costs 25 euros a night.','travel','B1','noun',false),
  w('en','to navigate','naviguer','To find your way','I use my phone to navigate.','travel','B1','verb',false),

  // ===== ANGLAIS - TRAVEL - B2 =====
  w('en','commute','trajet domicile-travail','Regular travel to work','My commute takes 45 minutes.','travel','B2','noun',false),
  w('en','expedition','expédition','An organized journey for a purpose','They went on an expedition to the Arctic.','travel','B2','noun',false),
  w('en','nomad','nomade','A person who moves from place to place','Digital nomads work while traveling.','travel','B2','noun',false),
  w('en','pilgrimage','pèlerinage','A religious journey','They went on a pilgrimage to Mecca.','travel','B2','noun',false),
  w('en','sustainable tourism','tourisme durable','Travel that respects the environment','Sustainable tourism protects nature.','travel','B2','noun',false),
  w('en','to embark','embarquer','To go onto a ship or airplane','Passengers began to embark at gate 7.','travel','B2','verb',false),
  w('en','to disembark','débarquer','To leave a ship or airplane','We disembarked after a smooth flight.','travel','B2','verb',false),
  w('en','immigration','immigration','Border control for entering a country','Immigration asked for my visa.','travel','B2','noun',false),
  w('en','quarantine','quarantaine','Isolation to prevent disease spread','Travelers may face quarantine.','travel','B2','noun',false),
  w('en','transit','transit','Passing through a place','We are in transit through Singapore.','travel','B2','noun',false),
  w('en','excursion','excursion','A short trip for pleasure','We went on an excursion to the mountains.','travel','B2','noun',false),
  w('en','voyage','voyage','A long journey, especially by sea','The voyage across the Atlantic took 5 days.','travel','B2','noun',false),
  w('en','to wander','errer','To walk without a destination','We wandered through the streets.','travel','B2','verb',false),
  w('en','to venture','s\'aventurer','To dare to go somewhere new','We ventured into the jungle.','travel','B2','verb',false),
  w('en','turbulence','turbulence','Sudden movements of air on a plane','The turbulence was quite strong.','travel','B2','noun',false),
  w('en','traverse','traverser','To travel across a region','We traversed the Sahara desert.','travel','B2','verb',false),
  w('en','odyssey','odyssée','A long and eventful journey','Their road trip was an odyssey.','travel','B2','noun',false),
  w('en','wanderlust','envie de voyager','A strong desire to travel','She has serious wanderlust.','travel','B2','noun',false),
  w('en','globetrotter','globe-trotteur','A person who travels widely','He is a true globetrotter.','travel','B2','noun',false),
  w('en','to relocate','déménager','To move to a new place','They relocated to Barcelona.','travel','B2','verb',false),

  // ===== ANGLAIS - MEETINGS - A1 =====
  w('en','meeting','réunion','A gathering of people to discuss','We have a meeting at 10.','meetings','A1','noun',true),
  w('en','office','bureau','A room for working','The office is on the third floor.','meetings','A1','noun',true),
  w('en','chair','chaise','A seat for one person','Please take a chair.','meetings','A1','noun',true),
  w('en','table','table','A flat surface for working','Put the files on the table.','meetings','A1','noun',true),
  w('en','email','email','An electronic message','I sent you an email.','meetings','A1','noun',true),
  w('en','name','nom','What someone is called','My name is John.','meetings','A1','noun',true),
  w('en','team','équipe','A group working together','Our team has five members.','meetings','A1','noun',true),
  w('en','boss','patron','A person in charge','The boss wants to see you.','meetings','A1','noun',true),
  w('en','question','question','Something asked to get information','Do you have a question?','meetings','A1','noun',true),
  w('en','answer','réponse','A reply to a question','I don\'t know the answer.','meetings','A1','noun',true),
  w('en','time','heure','A point in the day','What time is the meeting?','meetings','A1','noun',true),
  w('en','today','aujourd\'hui','This present day','Today is Monday.','meetings','A1','adverb',true),
  w('en','tomorrow','demain','The day after today','The meeting is tomorrow.','meetings','A1','adverb',true),
  w('en','phone','téléphone','A device for communication','My phone is ringing.','meetings','A1','noun',true),
  w('en','computer','ordinateur','An electronic device','I use a computer for work.','meetings','A1','noun',true),
  w('en','document','document','A paper with information','Please read this document.','meetings','A1','noun',true),
  w('en','colleague','collègue','A person you work with','She is my colleague.','meetings','A1','noun',true),
  w('en','project','projet','A planned piece of work','This is an important project.','meetings','A1','noun',true),
  w('en','report','rapport','A document with findings','The report is ready.','meetings','A1','noun',true),
  w('en','schedule','planning','A plan of activities','Check the schedule.','meetings','A1','noun',true),

  // ===== ANGLAIS - MEETINGS - A2 =====
  w('en','agenda','ordre du jour','A list of items to discuss','Let me check the agenda.','meetings','A2','noun',true),
  w('en','deadline','date limite','The latest time to finish','The deadline is Friday.','meetings','A2','noun',true),
  w('en','feedback','retour','Comments about performance','I need your feedback.','meetings','A2','noun',true),
  w('en','presentation','présentation','Showing information to a group','She gave a great presentation.','meetings','A2','noun',true),
  w('en','objective','objectif','A goal to achieve','What is the main objective?','meetings','A2','noun',true),
  w('en','minutes','compte-rendu','A written record of a meeting','Who is taking the minutes?','meetings','A2','noun',true),
  w('en','follow-up','suivi','Actions after a meeting','Let\'s plan a follow-up.','meetings','A2','noun',true),
  w('en','to discuss','discuter','To talk about a topic','We need to discuss the budget.','meetings','A2','verb',true),
  w('en','to agree','être d\'accord','To have the same opinion','I agree with your proposal.','meetings','A2','verb',true),
  w('en','to postpone','reporter','To delay to a later time','Let\'s postpone the meeting.','meetings','A2','verb',true),
  w('en','conference call','conférence téléphonique','A phone meeting with many people','Join the conference call at 3.','meetings','A2','noun',true),
  w('en','to summarize','résumer','To give a brief overview','Can you summarize the key points?','meetings','A2','verb',true),
  w('en','action item','point d\'action','A task assigned during a meeting','Each person has an action item.','meetings','A2','noun',true),
  w('en','to delegate','déléguer','To assign a task to someone','I\'ll delegate this to the team.','meetings','A2','verb',true),
  w('en','attendee','participant','A person at a meeting','All attendees received the agenda.','meetings','A2','noun',true),
  w('en','to update','mettre à jour','To give the latest information','Please update us on the project.','meetings','A2','verb',true),
  w('en','to approve','approuver','To officially agree','The board approved the budget.','meetings','A2','verb',true),
  w('en','slide','diapositive','One page of a presentation','Go to slide five.','meetings','A2','noun',true),
  w('en','brainstorm','remue-méninges','To generate ideas as a group','Let\'s brainstorm solutions.','meetings','A2','verb',true),
  w('en','stakeholder','partie prenante','A person with interest in a project','We need stakeholder approval.','meetings','A2','noun',true),

  // ===== ANGLAIS - MEETINGS - B1 =====
  w('en','to chair','présider','To lead a meeting','Who will chair the meeting?','meetings','B1','verb',true),
  w('en','consensus','consensus','General agreement','We reached a consensus.','meetings','B1','noun',true),
  w('en','milestone','jalon','An important event in a project','We reached a key milestone.','meetings','B1','noun',true),
  w('en','KPI','KPI','Key Performance Indicator','Review the KPIs monthly.','meetings','B1','noun',true),
  w('en','to escalate','escalader','To raise to a higher level','We need to escalate this issue.','meetings','B1','verb',true),
  w('en','quarterly','trimestriel','Happening every three months','The quarterly review is next week.','meetings','B1','adjective',true),
  w('en','to allocate','allouer','To distribute resources','We allocated budget for marketing.','meetings','B1','verb',true),
  w('en','takeaway','point clé','The main message from a meeting','The key takeaway is we need more time.','meetings','B1','noun',true),
  w('en','roundtable','table ronde','A discussion where all are equal','We had a roundtable on strategy.','meetings','B1','noun',true),
  w('en','deliverable','livrable','A result to be produced','The deliverable is due Friday.','meetings','B1','noun',true),
  w('en','to prioritize','prioriser','To rank in order of importance','We need to prioritize tasks.','meetings','B1','verb',true),
  w('en','bottleneck','goulot d\'étranglement','A point of congestion','Testing is the bottleneck.','meetings','B1','noun',true),
  w('en','workflow','flux de travail','A sequence of work processes','Let\'s improve the workflow.','meetings','B1','noun',true),
  w('en','to streamline','optimiser','To make more efficient','We streamlined the process.','meetings','B1','verb',true),
  w('en','benchmark','référence','A standard for comparison','We used industry benchmarks.','meetings','B1','noun',true),
  w('en','to implement','implémenter','To put a plan into action','We will implement the changes.','meetings','B1','verb',true),
  w('en','roadmap','feuille de route','A strategic plan','Here is the product roadmap.','meetings','B1','noun',true),
  w('en','scope','périmètre','The extent of a project','Define the project scope.','meetings','B1','noun',true),
  w('en','alignment','alignement','Agreement on direction','We need team alignment.','meetings','B1','noun',true),
  w('en','to review','passer en revue','To examine something carefully','Let\'s review the proposal.','meetings','B1','verb',true),

  // ===== ANGLAIS - MEETINGS - B2 =====
  w('en','accountability','responsabilité','Being responsible for results','Accountability is key in our team.','meetings','B2','noun',true),
  w('en','cross-functional','transversal','Involving different departments','A cross-functional team was formed.','meetings','B2','adjective',true),
  w('en','synergy','synergie','Combined effect greater than parts','The merger created synergy.','meetings','B2','noun',true),
  w('en','to leverage','tirer parti de','To use to maximum advantage','We can leverage our expertise.','meetings','B2','verb',true),
  w('en','scalability','évolutivité','Ability to grow','The solution offers scalability.','meetings','B2','noun',true),
  w('en','to pivot','pivoter','To change strategy','We need to pivot our approach.','meetings','B2','verb',true),
  w('en','due diligence','due diligence','Thorough investigation before a decision','We completed due diligence.','meetings','B2','noun',true),
  w('en','stakeholder management','gestion des parties prenantes','Managing interested parties','Stakeholder management is critical.','meetings','B2','noun',true),
  w('en','to onboard','intégrer','To integrate a new team member','We will onboard three people.','meetings','B2','verb',true),
  w('en','retrospective','rétrospective','A review of past performance','The sprint retrospective was useful.','meetings','B2','noun',true),
  w('en','value proposition','proposition de valeur','The benefit offered','Define the value proposition.','meetings','B2','noun',true),
  w('en','to mitigate','atténuer','To reduce risk or impact','We must mitigate the risk.','meetings','B2','verb',true),
  w('en','to facilitate','faciliter','To make a process easier','She facilitated the workshop.','meetings','B2','verb',true),
  w('en','to consolidate','consolider','To combine and strengthen','Let\'s consolidate the reports.','meetings','B2','verb',true),
  w('en','governance','gouvernance','The system of managing','Improve governance structures.','meetings','B2','noun',true),
  w('en','to advocate','plaider pour','To publicly support','I advocate for transparency.','meetings','B2','verb',true),
  w('en','disruption','disruption','Major change to an industry','Digital disruption is real.','meetings','B2','noun',true),
  w('en','to iterate','itérer','To repeat and improve','We iterate on the design.','meetings','B2','verb',true),
  w('en','bandwidth','bande passante','Available capacity to work','I don\'t have the bandwidth.','meetings','B2','noun',true),
  w('en','proactive','proactif','Acting before problems arise','Be proactive, not reactive.','meetings','B2','adjective',true),

  // ===== ANGLAIS - RISK MANAGEMENT - A1 =====
  w('en','risk','risque','The possibility of something bad','There is a risk of delay.','risk','A1','noun',true),
  w('en','safety','sécurité','Being protected from danger','Safety is our priority.','risk','A1','noun',true),
  w('en','problem','problème','A difficulty to solve','We have a problem.','risk','A1','noun',true),
  w('en','danger','danger','A situation that could cause harm','Danger! Do not enter.','risk','A1','noun',true),
  w('en','rule','règle','An instruction to follow','Follow the rules.','risk','A1','noun',true),
  w('en','check','vérification','To examine something','Please check the document.','risk','A1','noun',true),
  w('en','control','contrôle','The power to manage something','Quality control is important.','risk','A1','noun',true),
  w('en','error','erreur','A mistake','I found an error.','risk','A1','noun',true),
  w('en','loss','perte','When something is lost','The loss was significant.','risk','A1','noun',true),
  w('en','plan','plan','A detailed proposal','We need a plan.','risk','A1','noun',true),
  w('en','test','test','An examination','We did a test.','risk','A1','noun',true),
  w('en','alert','alerte','A warning of danger','There is an alert.','risk','A1','noun',true),
  w('en','fire','incendie','Combustion with flames','Fire safety is essential.','risk','A1','noun',true),
  w('en','accident','accident','An unexpected harmful event','There was an accident.','risk','A1','noun',true),
  w('en','insurance','assurance','Protection against loss','Get insurance for your car.','risk','A1','noun',true),
  w('en','protect','protéger','To keep safe from harm','We must protect our data.','risk','A1','verb',true),
  w('en','warning','avertissement','A notice of danger','Read the warning signs.','risk','A1','noun',true),
  w('en','emergency','urgence','A serious unexpected situation','Call 112 in an emergency.','risk','A1','noun',true),
  w('en','security','sécurité','Protection against threats','Security is everyone\'s job.','risk','A1','noun',true),
  w('en','password','mot de passe','A secret word for access','Change your password regularly.','risk','A1','noun',true),

  // ===== ANGLAIS - RISK - A2 =====
  w('en','assessment','évaluation','Judging the value or nature','Do a risk assessment first.','risk','A2','noun',true),
  w('en','compliance','conformité','Following rules and laws','Ensure compliance with regulations.','risk','A2','noun',true),
  w('en','fraud','fraude','Criminal deception for gain','Fraud was detected in the accounts.','risk','A2','noun',true),
  w('en','threat','menace','A possible source of danger','Cyber threats are increasing.','risk','A2','noun',true),
  w('en','vulnerability','vulnérabilité','A weakness that can be exploited','The system has a vulnerability.','risk','A2','noun',true),
  w('en','audit','audit','An official inspection','The annual audit starts Monday.','risk','A2','noun',true),
  w('en','breach','violation','A failure to comply','There was a data breach.','risk','A2','noun',true),
  w('en','to monitor','surveiller','To watch and check over time','We monitor risks daily.','risk','A2','verb',true),
  w('en','to report','signaler','To give information about','Report any incidents immediately.','risk','A2','verb',true),
  w('en','to prevent','prévenir','To stop from happening','We must prevent data loss.','risk','A2','verb',true),
  w('en','backup','sauvegarde','A copy for safety','Always make a backup.','risk','A2','noun',true),
  w('en','policy','politique','A set of rules','Read the security policy.','risk','A2','noun',true),
  w('en','incident','incident','An unexpected event','Report every incident.','risk','A2','noun',true),
  w('en','regulation','réglementation','An official rule','New regulations apply next month.','risk','A2','noun',true),
  w('en','to identify','identifier','To recognize something','Identify the main risks.','risk','A2','verb',true),
  w('en','procedure','procédure','A set of steps to follow','Follow the emergency procedure.','risk','A2','noun',true),
  w('en','to evaluate','évaluer','To judge the quality','Evaluate the impact.','risk','A2','verb',true),
  w('en','impact','impact','A strong effect','The impact was minimal.','risk','A2','noun',true),
  w('en','stakeholder','partie prenante','A person with an interest','Inform all stakeholders.','risk','A2','noun',true),
  w('en','to mitigate','atténuer','To reduce the severity','Mitigate the risk quickly.','risk','A2','verb',true),

  // ===== ANGLAIS - RISK - B1 =====
  w('en','contingency plan','plan de contingence','A plan for unexpected events','Activate the contingency plan.','risk','B1','noun',true),
  w('en','due diligence','diligence raisonnable','Careful investigation','Perform due diligence.','risk','B1','noun',true),
  w('en','exposure','exposition','The degree of risk faced','Our exposure is limited.','risk','B1','noun',true),
  w('en','internal control','contrôle interne','Processes to ensure goals are met','Strengthen internal controls.','risk','B1','noun',true),
  w('en','likelihood','probabilité','The chance of something happening','Assess the likelihood of failure.','risk','B1','noun',true),
  w('en','risk appetite','appétence au risque','The level of risk accepted','Define the risk appetite.','risk','B1','noun',true),
  w('en','risk register','registre des risques','A document listing all risks','Update the risk register.','risk','B1','noun',true),
  w('en','to escalate','faire remonter','To refer to a higher authority','Escalate critical issues.','risk','B1','verb',true),
  w('en','to remediate','remédier','To fix a problem','Remediate the vulnerability.','risk','B1','verb',true),
  w('en','whistleblower','lanceur d\'alerte','A person who reports wrongdoing','Protect the whistleblower.','risk','B1','noun',true),
  w('en','segregation of duties','séparation des tâches','Dividing tasks to prevent fraud','Ensure segregation of duties.','risk','B1','noun',true),
  w('en','residual risk','risque résiduel','Risk remaining after controls','Evaluate the residual risk.','risk','B1','noun',true),
  w('en','inherent risk','risque inhérent','Risk before any controls','Inherent risk is high here.','risk','B1','noun',true),
  w('en','to disclose','divulguer','To make information public','Disclose the conflict of interest.','risk','B1','verb',true),
  w('en','to enforce','faire respecter','To make sure rules are followed','Enforce the security policy.','risk','B1','verb',true),
  w('en','risk matrix','matrice des risques','A tool to assess risks','Use the risk matrix.','risk','B1','noun',true),
  w('en','tolerance','tolérance','Acceptable level of variation','Define your risk tolerance.','risk','B1','noun',true),
  w('en','to quantify','quantifier','To measure in numbers','Quantify the potential loss.','risk','B1','verb',true),
  w('en','business continuity','continuité d\'activité','Ability to continue operations','Test the business continuity plan.','risk','B1','noun',true),
  w('en','cyber attack','cyberattaque','An attack on computer systems','We detected a cyber attack.','risk','B1','noun',true),

  // ===== ANGLAIS - RISK - B2 =====
  w('en','enterprise risk management','gestion des risques d\'entreprise','Holistic approach to risk','Implement enterprise risk management.','risk','B2','noun',true),
  w('en','key risk indicator','indicateur de risque clé','A metric predicting risk','Monitor key risk indicators.','risk','B2','noun',true),
  w('en','risk-adjusted return','rendement ajusté au risque','Return considering the risk','Calculate risk-adjusted returns.','risk','B2','noun',true),
  w('en','operational resilience','résilience opérationnelle','Ability to withstand disruptions','Build operational resilience.','risk','B2','noun',true),
  w('en','systemic risk','risque systémique','Risk affecting the entire system','Systemic risk threatens the market.','risk','B2','noun',true),
  w('en','counterparty risk','risque de contrepartie','Risk the other party defaults','Assess counterparty risk.','risk','B2','noun',true),
  w('en','stress test','test de résistance','Simulating extreme scenarios','Run a stress test on the portfolio.','risk','B2','noun',true),
  w('en','to hedge','couvrir','To protect against financial risk','We hedged our currency exposure.','risk','B2','verb',true),
  w('en','reputational risk','risque de réputation','Risk of damage to reputation','Guard against reputational risk.','risk','B2','noun',true),
  w('en','scenario analysis','analyse de scénarios','Evaluating possible future events','Conduct a scenario analysis.','risk','B2','noun',true),
  w('en','regulatory framework','cadre réglementaire','System of rules and regulations','Comply with the regulatory framework.','risk','B2','noun',true),
  w('en','materiality','matérialité','The significance of an item','Assess the materiality of the finding.','risk','B2','noun',true),
  w('en','fiduciary duty','obligation fiduciaire','Legal duty to act in trust','Directors have a fiduciary duty.','risk','B2','noun',true),
  w('en','to aggregate','agréger','To combine multiple items','Aggregate the risk exposures.','risk','B2','verb',true),
  w('en','three lines of defense','trois lignes de défense','A risk governance model','Apply the three lines of defense.','risk','B2','noun',true),
  w('en','to substantiate','étayer','To provide evidence','Substantiate the claim with data.','risk','B2','verb',true),
  w('en','adverse event','événement défavorable','An undesirable occurrence','Report any adverse events.','risk','B2','noun',true),
  w('en','to benchmark','référencer','To compare against standards','Benchmark our risk practices.','risk','B2','verb',true),
  w('en','risk culture','culture du risque','Organizational attitude to risk','Foster a strong risk culture.','risk','B2','noun',true),
  w('en','to remediate','corriger','To fix identified issues','Remediate audit findings promptly.','risk','B2','verb',true),

  // ===== ESPAGNOL - TRAVEL - A1 =====
  w('es','hola','bonjour','A greeting','Hola, ¿cómo estás?','travel','A1','interjection',false,'Un saludo','Un saludo usado al encontrarse'),
  w('es','adiós','au revoir','A farewell','Adiós, hasta mañana.','travel','A1','interjection',false,'Una despedida','Una expresión de despedida'),
  w('es','por favor','s\'il vous plaît','A polite request word','Un café, por favor.','travel','A1','adverb',false,'Una palabra de petición educada','Una palabra educada usada al pedir'),
  w('es','gracias','merci','Expression of thanks','Muchas gracias por tu ayuda.','travel','A1','interjection',false,'Expresión de gratitud','Expresión de gratitud'),
  w('es','billete','billet','A travel ticket','Necesito un billete de tren.','travel','A1','noun',false,'Un documento para viajar','Un documento de viaje'),
  w('es','aeropuerto','aéroport','A place for planes','El aeropuerto está lejos.','travel','A1','noun',false,'Un lugar para aviones','Un lugar donde despegan y aterrizan aviones'),
  w('es','hotel','hôtel','A place to sleep','El hotel es muy bonito.','travel','A1','noun',false,'Un lugar para dormir','Un lugar para dormir durante el viaje'),
  w('es','tren','train','A rail vehicle','El tren sale a las nueve.','travel','A1','noun',false,'Un vehículo sobre rieles','Un vehículo que circula sobre rieles'),
  w('es','autobús','bus','A large public vehicle','Voy en autobús al trabajo.','travel','A1','noun',false,'Un gran vehículo público','Un gran vehículo para transporte público'),
  w('es','mapa','carte','A drawing of a region','¿Tienes un mapa de la ciudad?','travel','A1','noun',false,'Un dibujo de una región','Un dibujo de una región o país'),
  w('es','pasaporte','passeport','Travel document','No olvides tu pasaporte.','travel','A1','noun',false,'Documento oficial de viaje','Un documento oficial para viajar'),
  w('es','maleta','valise','A travel case','Mi maleta es grande.','travel','A1','noun',false,'Un estuche de viaje','Un estuche para transportar ropa'),
  w('es','taxi','taxi','A hired car','Tomemos un taxi al hotel.','travel','A1','noun',false,'Un coche alquilado','Un automóvil de alquiler'),
  w('es','restaurante','restaurant','A place to eat','Hay un restaurante cerca.','travel','A1','noun',false,'Un lugar para comer','Un lugar para comer comidas'),
  w('es','agua','eau','A clear liquid','¿Puedo tener agua, por favor?','travel','A1','noun',false,'Un líquido claro','Un líquido claro para beber'),
  w('es','habitación','chambre','A room for sleeping','La habitación tiene buena vista.','travel','A1','noun',false,'Una habitación para dormir','Un espacio en un edificio para dormir'),
  w('es','dinero','argent','Currency','Necesito cambiar dinero.','travel','A1','noun',false,'Moneda','Moneda usada para comprar cosas'),
  w('es','playa','plage','A sandy area by the sea','Vamos a la playa.','travel','A1','noun',false,'Una zona arenosa junto al mar','Una zona arenosa cerca del mar'),
  w('es','ciudad','ville','A large town','Madrid es una gran ciudad.','travel','A1','noun',false,'Una ciudad grande','Una ciudad grande'),
  w('es','ayuda','aide','Assistance','Necesito ayuda con mi maleta.','travel','A1','noun',false,'Asistencia','La asistencia dada a alguien'),

  // ===== ESPAGNOL - TRAVEL - A2 =====
  w('es','equipaje','bagages','Travel bags','¿Dónde está el equipaje?','travel','A2','noun',false,'Bolsas de viaje','Bolsas y maletas para viajar'),
  w('es','salida','départ','The act of leaving','La salida es a las tres.','travel','A2','noun',false,'El acto de partir','El acto de dejar un lugar'),
  w('es','llegada','arrivée','The act of arriving','Comprueba la hora de llegada.','travel','A2','noun',false,'El acto de llegar','El acto de llegar a un lugar'),
  w('es','reserva','réservation','A booking','Tengo una reserva para dos.','travel','A2','noun',false,'Una reservación','Una reserva hecha por adelantado'),
  w('es','vuelo','vol','A journey by air','El vuelo dura dos horas.','travel','A2','noun',false,'Un viaje por aire','Un viaje en avión'),
  w('es','moneda','devise','The money used','¿Qué moneda usan aquí?','travel','A2','noun',false,'Dinero de un país','La moneda usada en un país'),
  w('es','guía','guide','A travel book or person','Compré una guía de Italia.','travel','A2','noun',false,'Un libro de viaje','Un libro con información de viaje'),
  w('es','alojamiento','hébergement','A place to stay','Encontramos alojamiento barato.','travel','A2','noun',false,'Un lugar para hospedarse','Un lugar para quedarse'),
  w('es','destino','destination','Where you are going','¿Cuál es tu destino?','travel','A2','noun',false,'Lugar a donde vas','El lugar al que vas'),
  w('es','retraso','retard','When something is late','Hay un retraso de 30 minutos.','travel','A2','noun',false,'Cuando algo es tardío','Cuando algo se retrasa'),
  w('es','tarjeta de embarque','carte d\'embarquement','Boarding document','Muestra tu tarjeta de embarque.','travel','A2','noun',false,'Documento de embarque','Un documento necesario para abordar un avión'),
  w('es','aduana','douane','Border checks','Pasamos la aduana rápido.','travel','A2','noun',false,'Controles fronterizos','El lugar en las fronteras para revisiones'),
  w('es','tipo de cambio','taux de change','Currency conversion rate','El tipo de cambio es favorable.','travel','A2','noun',false,'Tasa de conversión de moneda','La tasa para convertir monedas'),
  w('es','recuerdo','souvenir','An object from a trip','Compré un recuerdo para mamá.','travel','A2','noun',false,'Un objeto de un viaje','Un objeto comprado para recordar un viaje'),
  w('es','itinerario','itinéraire','A planned route','Nuestro itinerario incluye Roma.','travel','A2','noun',false,'Una ruta planificada','Una ruta de viaje planeada'),
  w('es','registro','enregistrement','Hotel or airport process','El registro empieza a las dos.','travel','A2','noun',false,'Proceso de registro','El proceso en un hotel o aeropuerto'),
  w('es','excursión','excursion','A short trip','Hicimos una excursión al campo.','travel','A2','noun',false,'Un viaje corto','Un viaje corto para pasear'),
  w('es','dirección','direction','The way to go','¿Me puedes dar la dirección?','travel','A2','noun',false,'La forma de ir','El camino a seguir'),
  w('es','andén','quai','Train waiting area','El tren sale del andén tres.','travel','A2','noun',false,'Zona de espera de tren','Donde esperas el tren'),
  w('es','turista','touriste','A person visiting a place','Hay muchos turistas aquí.','travel','A2','noun',false,'Una persona de visita','Una persona que visita un lugar'),
];
