// ==========================================
// LINGUALEARN - LOT 2 : Banque Lecture
// EN (6 textes: 1/niveau A1-B2 + 2 GRC) + ES (2 textes A1-A2)
// ==========================================

import { ReadingText } from './bankTypes';

export const BANK_READING: ReadingText[] = [
  // ===== ANGLAIS - TRAVEL - A1 =====
  { id:'rd_en_01', language:'en', level:'A1', theme:'travel', title:'My First Trip',
    body_text:`I am going on a trip. I have my passport and my suitcase. I take a taxi to the airport. The airport is very big. I check in and get my boarding pass. I wait at the gate. The plane is ready. I find my seat. The flight is two hours. I am happy. I arrive at the hotel. The room is nice. I am tired but excited. Tomorrow I will explore the city. I want to see the beach and the old town. I have a map. This is a great trip.` },

  // ===== ANGLAIS - TRAVEL - A2 =====
  { id:'rd_en_02', language:'en', level:'A2', theme:'travel', title:'A Weekend in Barcelona',
    body_text:`Last weekend, I went to Barcelona with my friend. We took a flight from Paris. The flight was only two hours. We arrived at the airport and took a bus to the city center. Our hotel was near Las Ramblas, a famous street with many shops and restaurants. On Saturday, we visited the Sagrada Familia. It is a beautiful church designed by Gaudí. We also walked around the Gothic Quarter and tried some tapas. The food was delicious. On Sunday, we went to the beach. The weather was warm and sunny. We swam in the sea and relaxed on the sand. In the evening, we had dinner at a small restaurant near the port. I ordered paella. It was the best paella I have ever tasted. We came back to Paris on Sunday night. It was a short but wonderful trip.` },

  // ===== ANGLAIS - TRAVEL - B1 =====
  { id:'rd_en_03', language:'en', level:'B1', theme:'travel', title:'Backpacking Through Southeast Asia',
    body_text:`After finishing university, I decided to go backpacking through Southeast Asia for three months. I started in Thailand, where I spent two weeks exploring Bangkok and the northern city of Chiang Mai. The temples were breathtaking, and the street food was incredibly cheap and delicious. From Thailand, I traveled by bus to Cambodia to visit Angkor Wat. Watching the sunrise over the ancient temples was one of the most memorable experiences of my life. Next, I flew to Vietnam and traveled from north to south. I loved the chaos of Hanoi and the beauty of Ha Long Bay. The overnight train from Hanoi to Hue was an adventure in itself. I met travelers from all over the world, and we shared stories and travel tips. One thing I learned is that traveling slowly allows you to really understand a culture. Instead of rushing from one tourist attraction to another, I spent time in local markets, talked to people, and tried to learn a few words in each language. Backpacking taught me independence, flexibility, and the importance of stepping outside my comfort zone.` },

  // ===== ANGLAIS - TRAVEL - B2 =====
  { id:'rd_en_04', language:'en', level:'B2', theme:'travel', title:'The Ethics of Modern Tourism',
    body_text:`Tourism is one of the largest industries in the world, contributing significantly to global GDP and providing employment for millions of people. However, the rapid growth of mass tourism has raised serious ethical and environmental concerns. Overtourism in cities like Venice, Barcelona, and Dubrovnik has led to rising housing costs, environmental degradation, and a loss of local character. Residents in these cities have staged protests against the influx of tourists, arguing that their quality of life has deteriorated. Sustainable tourism offers an alternative approach. It emphasizes minimizing environmental impact, supporting local economies, and respecting cultural heritage. Eco-lodges, community-based tourism, and carbon offset programs are examples of initiatives that aim to make travel more responsible. Critics argue, however, that sustainable tourism remains a niche market that does not address the systemic issues of the industry. The COVID-19 pandemic provided an unexpected opportunity to rethink tourism. With international travel severely restricted, many destinations experienced a period of environmental recovery. As the world reopens, the challenge is to rebuild the tourism industry in a way that balances economic growth with environmental sustainability and social equity.` },

  // ===== ANGLAIS - GRC (MEETINGS/RISK) - B1 =====
  { id:'rd_en_05', language:'en', level:'B1', theme:'meetings', title:'How to Run an Effective Meeting',
    body_text:`Meetings are an essential part of professional life, but they are often criticized for being unproductive. According to several studies, the average professional spends about 15 hours per week in meetings, and nearly 70% of those meetings are considered unnecessary or poorly organized. So how can we make meetings more effective? First, every meeting should have a clear agenda distributed in advance. This allows participants to prepare and ensures that the discussion stays focused. The agenda should include the topics to be discussed, the time allocated for each topic, and the expected outcomes. Second, the meeting should have a designated facilitator who keeps the conversation on track and ensures that everyone has a chance to speak. Third, action items should be clearly defined at the end of the meeting, with specific responsibilities and deadlines assigned to individuals. Finally, meeting notes or minutes should be shared with all participants within 24 hours. By following these simple guidelines, organizations can reduce meeting time by up to 30% while improving the quality of decisions made.` },

  // ===== ANGLAIS - GRC (RISK) - B2 =====
  { id:'rd_en_06', language:'en', level:'B2', theme:'risk', title:'Enterprise Risk Management in the Digital Age',
    body_text:`Enterprise Risk Management (ERM) has evolved significantly over the past two decades. What was once a compliance-driven exercise focused primarily on financial and operational risks has become a strategic discipline that encompasses cyber threats, reputational risks, and emerging challenges such as climate change and geopolitical instability. The COSO framework, updated in 2017, provides a comprehensive approach to ERM that integrates risk management with strategy and performance. It emphasizes the importance of risk culture, governance, and the alignment of risk appetite with organizational objectives. In the digital age, cybersecurity has become one of the most critical risk categories. The average cost of a data breach exceeded $4 million in 2023, and ransomware attacks have increased by over 150% in the past three years. Organizations must implement robust controls, including multi-factor authentication, encryption, and regular penetration testing. The three lines of defense model remains a cornerstone of effective risk governance. The first line consists of operational management, which owns and manages risks on a daily basis. The second line provides oversight through risk management and compliance functions. The third line offers independent assurance through internal audit. As risks become more interconnected and complex, organizations that invest in proactive risk management will be better positioned to navigate uncertainty and create sustainable value.` },

  // ===== ESPAGNOL - TRAVEL - A1 =====
  { id:'rd_es_01', language:'es', level:'A1', theme:'travel', title:'Mi primer viaje',
    body_text:`Voy a hacer un viaje. Tengo mi pasaporte y mi maleta. Tomo un taxi al aeropuerto. El aeropuerto es muy grande. Hago el registro y recibo mi tarjeta de embarque. Espero en la puerta. El avión está listo. Encuentro mi asiento. El vuelo es de dos horas. Estoy contento. Llego al hotel. La habitación es bonita. Estoy cansado pero emocionado. Mañana voy a explorar la ciudad. Quiero ver la playa y el centro histórico. Tengo un mapa. Es un viaje muy bonito.` },

  // ===== ESPAGNOL - TRAVEL - A2 =====
  { id:'rd_es_02', language:'es', level:'A2', theme:'travel', title:'Un fin de semana en Madrid',
    body_text:`El fin de semana pasado, fui a Madrid con mi amiga. Tomamos un vuelo desde París. El vuelo fue de solo dos horas. Llegamos al aeropuerto y tomamos el metro al centro de la ciudad. Nuestro hotel estaba cerca de la Puerta del Sol, una plaza famosa con muchas tiendas y restaurantes. El sábado, visitamos el Museo del Prado. Es un museo muy grande con pinturas increíbles. También caminamos por el Parque del Retiro y comimos churros con chocolate. La comida estaba deliciosa. El domingo, fuimos al mercado de San Miguel. Probamos tapas y vinos españoles. Por la noche, cenamos en un restaurante pequeño. Pedí una tortilla española. Fue la mejor tortilla que he probado. Volvimos a París el domingo por la noche. Fue un viaje corto pero maravilloso.` },
];
